### ISSUE TITLE
Work on issues

### ISSUE THREAD

**Issue by switchhax** [vhf/free-programming-books#1192]
I recognized that PRs are relatively fast merged into master. 
But what bothers me is that some issues are older than 2-3 months, and it seems no work on them has been done so far. I think some could/should be closed after the material is analyzed and/or merged.

**Comment by onebree** [comment]
ping @borgified

**Comment by switchhax** [comment]
Yeah, but these are from other people. They made their PRs and didn´t close their issue. Or the issue is just unnessary cause its already resolved. I´m not a maintainer, so i can close, what should be closed :D

**Comment by borgified** [comment]
thx for the ping @onebree im back and can help weed out bad links now

**Comment by borgified** [comment]
i would like to add
```
http://sarabander.github.io/sicp/html/index.xhtml
```
but im not sure what the policy is for adding multiple links to the same book. personally i think it can only benefit us as it gives us an alternate way to get to the book should one of the links go bad. is there a particular format for this? do we just add another entry as if it was a separate book?
hoping @vhf can help us answer

**Comment by switchhax** [comment]
If the book appears in a new edition, then two separate links with a note about the edition. Sometimes the content differ. If it´s the book, only better looking or so (same format e.g .pdf), replace it. If one is a webpage, the other one an ebook, take both with a hint on the "medium". 
Some thoughts i had.

**Comment by vhf** [comment]
Hey, thanks for the great inputs! I would go with the way @switchhax described.

**Comment by borgified** [comment]
:+1:

**Comment by switchhax** [comment]
Nice how you directly update the `CONTRIBUTING.md` :+1:

**Comment by borgified** [comment]
oh i have write access thats why :)

**Comment by switchhax** [comment]
Yes, i know :D
