### ISSUE TITLE
It would be helpful to specify access requirements

### ISSUE THREAD

**Issue by ghost** [vhf/free-programming-books#1223]
I have being following this repo for a few days and checked out some of the books referenced. Some links point to files stored behind subscription barriers (i.e. you must join a list a cop junk mail to read the book). These types of books are rarely 'free' per se. Maybe submitters should flag if a link points to a subscription site or has particular license constraints.

**Comment by borgified** [comment]
yea i know what you mean, i try to avoid merging these in. @vhf can weigh in about these too.

**Comment by onebree** [comment]
:+1: for this issue! I think it is important to note when accounts or other requirements are necessary to obtain a book/course. It isn't truly free if you need to provide something on your end. I think we can assume account logins for sites like Coursera, because how else are you to track your progress?

@SimonChristopherCropper I would suggest opening a PR noting which links require logins, etc. We should amend (add info) to the list, at the very least, before removing helpful references.

**Comment by vhf** [comment]
I agree with @onebree !

**Comment by DavidMetcalfe** [comment]
@onebree @vhf Is it preferable to separate such links into their own category, or just add a note? 

As my focus on documentation is with readability, my concern with notes (granting there might be numerous problem links present) is we'll bloat the existing document vertically, while adding no real value. That is, people will inherently gravitate towards easy access and truly "free" content over paywalls or the like, so it seems more apt to separate these into their own **Subscription**-based category within the documents.

**Comment by onebree** [comment]
As I said before, we should change as little of the current links as possible, until we research further. I think an "account required" category would be nice -- the word "subscription" makes me think that money is involved (and not free).

I could create a PR in a couple of days to add this section to all the English docs...

**Comment by DavidMetcalfe** [comment]
@onebree I lean towards your word choice here. "Account required" or "Signup required" is definitely less suggestive than "Subscription."

**Comment by vhf** [comment]
Agreed. If you have some free time, I'd gladly accept a PR annotating such links with `*(account required)*`

**Comment by onebree** [comment]
@vhf I am unable to submit a PR at this time. Hopefully another person can!

**Comment by vhf** [comment]
No problem @onebree! You helped this repo a lot already, and it is/was much appreciated. You certainly noticed I closed a bunch of issues today. This one is still standing though, and I won't close it until it's fixed, by any contributor or by me. :)

**Comment by vhf** [comment]
#1746 made me realise I have not been clear about what I would prefer regarding this issue.

I suggest annotating links with *(account required)* when it applies, instead of creating a new category "Account Required" and duplicating sub-categories.

**Comment by rickytaki** [comment]
No @vhf, my bad!!! I was in a hurry and misunderstood the requirements! Sorry

**Comment by onebree** [comment]
@vhf  I think this issue should remain open until we put somewhere (maybe `CONTRIBUTING.md`?) these guidelines.

**Comment by vhf** [comment]
Oh I thought it was already in `CONTRIBUTING.md`. I'll add it.

**Comment by onebree** [comment]
Thank you. What are your thoughts on a table format? The raw markdown may not look as pretty, and added new columns will be a pain... I am not sure how this could be done elegantly, but just an idea.

**Comment by johnaoss** [comment]
Would something like [www.syncfusion.com](https://www.syncfusion.com/resources/techportal/ebooks/twitterbootstrap3) be against this then? It requires signing up for an account before access to the book is given.

**Comment by vhf** [comment]
@johnaoss it's not really against this. I think although syncfusion doesn't require an actual *account*, we should still annotate all syncfusion links with *account required*. I'm open to suggestions on this matter.

**Comment by ShipsWithCannons** [comment]
@onebree I suspect that's something for another issue.
