### ISSUE TITLE
Create "Computer Science" section in free-courses-en.md

### ISSUE THREAD

**Issue by cshubhamrao** [vhf/free-programming-books#1334]
Taking a look at the "Misc" section of `free-courses-en.md`, many courses seem to be CS related; then why not create a "Computer Science" section? This will aid those who are browsing this list.

The non-CS courses can be kept in "Misc" .

**Comment by cshubhamrao** [comment]
Resources of interest can be added to "Computer Science" section from this repo: https://github.com/prakhar1989/awesome-courses

**Comment by switchhax** [comment]
Some of them are already in our list, i will work on it in my holidays.
