### ISSUE TITLE
LaTeX : fusionner la section TeX

### ISSUE THREAD

**Issue by maieul** [vhf/free-programming-books#1367]
La section LaTeX contient 
- asymptote
- metapost
- tikz

et met tex à part. Or metapost peut fonctionner avec TeX. Donc a mon avis il faudrait
- soit sortir metapost et faire un renvoi, comme pour TeX
- soit regrouper cela dans une rubrique "(La)TeX et associés". Avec des sous rubriques, pas forcément dans l'ordre alphabétique.

**Comment by maieul** [comment]
un avis ? @vhf

**Comment by vhf** [comment]
Ça me semble effectivement une bonne idée. Je vote pour la deuxième solution. Merci!
