### ISSUE TITLE
Its not a book, but a good learning resource.

### ISSUE THREAD

**Issue by vixir** [vhf/free-programming-books#1388]
[link to CodeLearn!](http://www.codelearn.org/android-tutorial).

**Comment by cirosantilli** [comment]
I also wanted to make a blog list for great stuff like: http://www.geeksforgeeks.org/fundamentals-of-algorithms/ . I wonder if there would be too many? But the best websites are at least as good a books...

**Comment by alesegdia** [comment]
I would accept it since it seems like a good resource for learning Android. Personally, I like the learn-by-doing philosophy.

**Comment by vhf** [comment]
I'd accept a PR.
