### ISSUE TITLE
Mahout in Action

### ISSUE THREAD

**Issue by skategui** [vhf/free-programming-books#1394]
[Mahout in Action, by Sean Owen, Robin Anil, Ted Dunning, Ellen Friedman](http://openresearch.baidu.com/u/cms/www/201210/30144944cqmu.pdf)  (PDF)

**Comment by chrisspruck** [comment]
In looking at issues to help close, I saw that this links to a full copy of a commercial book found at http://www.manning.com/owen/. I suggest this be closed.
