### ISSUE TITLE
Broken URL Portuguese Java Course

### ISSUE THREAD

**Issue by leleonam** [vhf/free-programming-books#1419]
Here, we have a broken link for a java course in Youtube. The owner account is closed

https://github.com/vhf/free-programming-books/commit/937ab8f0986121ff26eb096ca8b9f104bde5c28f

**Comment by vhf** [comment]
Could you submit a PR to remove these entries please?

Thanks a lot.

**Comment by leleonam** [comment]
@vhf PR created :)

https://github.com/vhf/free-programming-books/pull/1420
