### ISSUE TITLE
Create gitbook stuffs

### ISSUE THREAD

**Issue by khajavi** [vhf/free-programming-books#1421]
Could I convert this repo to gitbook repo, and then pull request it?

**Comment by vhf** [comment]
I'm not so familiar with gitbook. What would be the pros and cons?

**Comment by cirosantilli** [comment]
@vhf PDF output is the only I can think of. Probably not worth it yet.

**Comment by borgified** [comment]
I took a closer look at gitbook. It's mainly for publishing your book that you create in your git repo. We are a collection of links, we don't have the actual text.
