### ISSUE TITLE
free-science-books

### ISSUE THREAD

**Issue by switchhax** [vhf/free-programming-books#1427]
What about a repository with/to gather free-science-books (called like this)?
I know it has nothing to do with programming and computer sciences, but other sciences are also interresting and i think a good list of resources will help many people.
So it could be nice to have such a list/repository.

**Comment by eshellman** [comment]
It's been really interesting to watch the FPB repo grow and help it along a bit now and then, and I'd be interested in ideas of how to do something similar for areas of science. Starting something new, you have the chance to change things you would do differently if you started over; I wonder what Victor would want to change.

I run https://unglue.it/ , I'm one of the folks behind GITenberg, and I'm friends with the guy behind the Penn Online Books page http://onlinebooks.library.upenn.edu/new.html . You could probably seed a science repo from OBP.

I'd like to see something with a bit more info- whether the books format and license, mostly. But maybe that's too much. For GITenberg, we're going to emphasize the metadata more.

**Comment by switchhax** [comment]
I dont really have redesign ideas, i like how free-programming-books is. Well i would chance the representing website totally, but nothing more.
I´m a bit short of time at the moment (writing exams after the holidays, which are a bit important for A-levels), so i thought i drop this idea here for a discussion.

**Comment by borgified** [comment]
and of course if you need those urls checked regularly, we can use borgified/url_checker. if you stick w/ the general formatting guidelines for adding new links, then it should work just fine.

**Comment by switchhax** [comment]
Of Course, but before i need to find some books :D

**Comment by onebree** [comment]
I think science books are harder to come by. I feel like those are more often paid-only because they are usually only for university... Where everything costs money and nothing is free

**Comment by aramisf** [comment]
:+1: Good idea.

**Comment by switchhax** [comment]
We will find some free good content, would be nice, if you could search too to get it a bit started. Well for a Video or a course list its a lot easier.

**Comment by onebree** [comment]
In my recent PR for fixing some of the broken links, I found that IEEE has free stuff. I think with science books, free content is best found in orgs like that, or with Wikibooks. This weekend, I will try to find some links, and post them here for review.

**Comment by onebree** [comment]
@switchhax and @borgified I think it would be best to send all science books to the above repo suggested. It is already established, so we will not be recreating the wheel. We can always make a "similar sites" section in the readme, linking to other "free-x-books" repos... Similar to how the Awesome Lists projects work.

**Comment by eshellman** [comment]
established, as of 20 minutes ago!

but I'll do a dump of books from unglue.it <http://unglue.it/> this weekend and we'll have a good starter set. unglue.it <http://unglue.it/> is narrower in the licensing it accepts because of its library focus, but f-p-b has definitely shown the value of casting a wider net.

**Comment by onebree** [comment]
@eshellman I did not even read the commit history. It looked established with all the language files in the root directory. Nevertheless, I still think science books should go to your repository, since you already made the effort of creating it.. I think it is great to have a foundation of free ebooks. I will check out the foundation site this weekend.

Maybe, just maybe, `free-books` should be an _organization_ on Github, where it collects all related free-XYZ-books repositories.

**Comment by onebree** [comment]
@eshellman Thank you for the invite. And Jersey Pride!

**Comment by switchhax** [comment]
I´m in for the german list  :) Well there i found some sites for it. Also for the english part. Maybe we need a list about online courses, screnncasts and problem-sets. They are easier to fill in some topics.

**Comment by onebree** [comment]
I propose we move all discussion to the free science books repository. And that this issue gets closed. I'm a contributor on the science one so I can help

**Comment by switchhax** [comment]
Ok, i for my would say that it should be called EBookFoundation instead of EbookFoundation.
