### ISSUE TITLE
page not found in free-programming-books-zh.md

### ISSUE THREAD

**Issue by huguangju** [vhf/free-programming-books#1479]
in [https://github.com/vhf/free-programming-books/blob/master/free-programming-books-zh.md](https://github.com/vhf/free-programming-books/blob/master/free-programming-books-zh.md)

[MIT 公开课](http://ocw.mit.edu/courses/translated-courses/simplified-chinese/) - http://ocw.mit.edu/courses/translated-courses/simplified-chinese/ Page not found

**Comment by borgified** [comment]
thx for reporting, this is also found in #1586
