### ISSUE TITLE
Date of book?

### ISSUE THREAD

**Issue by RobFl** [vhf/free-programming-books#1480]
Would be really helpful to see how old a book is, programming books evolve so fast and not all authors want the job to update every single time.

**Comment by borgified** [comment]
do you mean by when the book was published? this might be difficult as some are online resources w/o a "publishing date"

**Comment by onebree** [comment]
I agree. Online resources may automatically update their copyright dates, even if the content was not touched since 2013. For example, Codecademy, I believe, still teaches Ruby 1.9, even though it is no longer supported.
