### ISSUE TITLE
"Operating Systems - Prof. Subhashis Banerjee, IIT Delhi" is a course page

### ISSUE THREAD

**Issue by darkgeek** [vhf/free-programming-books#1537]
There's an `Operating Systems - Prof. Subhashis Banerjee, IIT Delhi` in `Operating Systems` section of the `free-programming-books.md`, however, it's a course page rather than a book online. What's more, many links in that page, including some web resources, are no longer available now. So, I think it would be better to remove it or put it elsewhere.

**Comment by borgified** [comment]
#1448 was merged in by @vhf
title suggests lecture notes but clicking on the link i just see links to tests and quizzes
maybe we move this to another file, though im not sure if it fits in `free-courses-en.md` either
