### ISSUE TITLE
C# Succinctly Book

### ISSUE THREAD

**Issue by arkydon** [vhf/free-programming-books#1541]
https://www.syncfusion.com/resources/techportal/ebookconfirm/csharp/sitevisitors

**Comment by borgified** [comment]
this one requires that you create an account first, not that it immediately disqualifies it from the list, but i think we want to add some special tag on it. something similar to what we do with pdfs (PDF) would work, i just dont know what though.

**Comment by arkydon** [comment]
You can fill in anything while creating the account, it won't check if the details entered are valid :-)
