### ISSUE TITLE
@php: PHP Objects, Patterns, and Practice

### ISSUE THREAD

**Issue by ndf4** [vhf/free-programming-books#1568]
Excellent book about OOP in PHP 5.x .

http://www.ycit-he.org/files/Resources/PHP%20Objects,%20Patterns,%20and%20Practice.pdf

Might it be added to the list?

**Comment by alameya** [comment]
:+1:

**Comment by vhf** [comment]
The homepage for this book seems to be: http://www.apress.com/9781430229254

and it does not look like a free book to me. Could you please provide some kind of proof that this book is indeed free?

Thanks

**Comment by fredericksilva** [comment]
+1 @vhf close Issue.

**Comment by borgified** [comment]
doesnt look free to me either. closing. if you can provide proof otherwise, i will can reopen.

**Comment by fredericksilva** [comment]
Thanks @borgified !! :+1:
