### ISSUE TITLE
Transfer ownership to org EbookFoundation?

### ISSUE THREAD

**Issue by onebree** [vhf/free-programming-books#1600]
@eshellman invited me to help out with the organization. So far, we only have a repo for science books. I think it would be great to transfer ownership to the organization. Of course, @vhf would be invited as an owner (speaking for @eshellman), with current collaborators set to the team for free-programming-books.

This is just a thought. I know FPB is already on the awesome list, but maybe we can start our own list, for just books/references?

Feel free to discuss, or even close this issue. Going out on a limb here

And if you think EbookFoundation's free science books should be on the awesome list, instead, then let me know, too

**Comment by eshellman** [comment]
If @vhf wants to drop out, that's one thing, but no need to fix something that isn't broken.

**Comment by onebree** [comment]
@eshellman then maybe we should move to the awesome list?
