### ISSUE TITLE
Broken Link for Java book

### ISSUE THREAD

**Issue by luminousbeam** [vhf/free-programming-books#1628]
3D Programming in Java - Daniel Selman

http://www.mat.uniroma2.it/~picard/SMC/didattica/materiali_did/Java/Java_3D/Java_3D_Programming.pdf

**Comment by missingdays** [comment]
What do you mean bey broken?
It opens fine for me

**Comment by luminousbeam** [comment]
I guess the link was down when I first came across it. It's working for me now! Sorry, I am closing the issue.
