### ISSUE TITLE
Clarification of "Graphic Pack" requirements in TODO

### ISSUE THREAD

**Issue by DavidMetcalfe** [vhf/free-programming-books#1676]
The TODO file has an item "Graphic Pack" under the **Getting the word out there** task, but I see no details anywhere about details on what would be desired as a contribution. Anything we might be able to add for contributors on this one?

**Comment by vhf** [comment]
This graphic pack idea wasn't mine, and I'm not sure we really need one.

I mean, a project logo would be nice, of course, but we already have the :books: emoji. :)

Anyway, I suggest we remove this item from the TODO. And why not removing the TODO file while we're at it? Alphabetical sorting is mostly done, and I don't merge non-alphabetically sorted PRs. I don't see the need for this TODO anymore.

What do you think?

**Comment by DavidMetcalfe** [comment]
@vhf Certainly makes sense then to remove the graphic pack part, yes.

I'm not against removing the TODO as long as you're good with the multilingual resources possibly remaining unsorted. Perhaps the TODO contents could be merged with **CONTRIBUTING.md**?

**Comment by onebree** [comment]
1. I think the TODO should live in a wiki article. It allows anyone to edit without affecting the commit history of the repo.
2. I do not think it should be added to the contrib file, which already asks you to ABC your links.
3. I can open a PR tonight that ABC's all the files. Should not be difficult.

**Comment by vhf** [comment]
Alright, let's do this! Thank you in advance.

**Comment by onebree** [comment]
@vhf I did not get to the PR last night... I will work on it this weekend.

**Comment by vhf** [comment]
Oh, I forgot that clicking "merge" automatically closes the referenced issue.

I'll reopen it until after the coming PR is merged. Thanks in advance!

**Comment by onebree** [comment]
I included this issue as a reference, because the main thing in this issue was removing or editing the TODO list, which I accomplished. Since ABCing is on the todo list, no need to open another issue. I was just busy last night and could not get to it.
