### ISSUE TITLE
Invalid header in the free-programming-books-ru.md

### ISSUE THREAD

**Issue by atrosinenko** [vhf/free-programming-books#1734]
There is a broken internal link "Open Source Ecosystem" in the `free-programming-books-ru.md` file. The link does not work because of misspelled header ("ecosytem" instead of "ecosystem"). Unfortunately, fixing this mistake will probably break links to this particular chapter of the file.

**Comment by TheSooth** [comment]
@atrosinenko it's already fixed in #1723
