### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by davisonio** [vhf/free-programming-books#1742]
**free-programming-books-es.md:**
- [x] http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-agile.pdf
- [x] http://sistop.gwolf.org/pdf/sistemas_operativos.pdf
- [x] http://gitimmersion.mx
- [x] http://www.compunauta.com/forums/linux/programacion/java/AprendiendoJava.pdf
- [x] http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-php.pdf
- [x] http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-python.pdf

**free-programming-books-id.md:**
- [x] http://www.ariona.net/ebook-belajar-html-dan-css/

**free-programming-books-jp.md:**
- [x] http://ap.kakoku.net/index.html
- [x] http://winscript.jp/powershell/202

**free-programming-books-pt_BR.md:**
- [x] http://ccsl.ime.usp.br/files/books/intro-java-cc.pdf
- [x] https://www.telecom.uff.br/pet/petws/downloads/apostilas/LINUX.pdf

**free-programming-books-tr.md:**
- [x] https://www.gitbook.io/book/vigo/ruby-101

**free-programming-books-zh.md:**
- [x] http://huyuefeng.me/intro-to-prog/
- [x] http://web.math.isu.edu.tw/yeh/HowTo/HowToTex/latex123.pdf
- [x] https://www.gitbook.io/book/numbbbbb/-the-swift-programming-language-
- [x] http://edu.51cto.com
- [x] http://yeomanjs.org
- [x] https://me.alipay.com/astaxie
- [x] http://www.w3school.com.cn/html5/
- [x] http://woodpecker.org.cn/diveintopython3/
- [x] http://woodpecker.org.cn/diveintopython/
- [x] http://woodpecker.org.cn/abyteofpython_cn/chinese/

**free-programming-books.md:**
- [x] http://static.fsf.org/nosvn/faif-2.0.pdf
- [x] http://blog.hit.edu.cn/jsx/upload/AT%EF%BC%86TAssemblyLanguage.pdf
- [x] http://media.developerforce.com/workbooks/HerokuPostgres_Workbooks_Web_Final.pdf
- [x] http://nlpwp.org/book/
- [x] http://www.mindview.net/Books/TIJ/
- [x] http://althing.cs.dartmouth.edu/local/www.acm.uiuc.edu/sigmil/RevEng/
- [x] https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/ProgrammingWithObjectiveC.pdf
- [x] https://github.com/renkun-ken/learnR

**Comment by vhf** [comment]
Thanks a lot!

I suggest we take care of #1743 first, and then get back to removing those after #1743 is merged.

**Comment by vhf** [comment]
Awesome work, many thanks!

I'm closing this for now as I expect to merge your PR very soon.
