### ISSUE TITLE
Page Not Found errors

### ISSUE THREAD

**Issue by gwsounddsg** [vhf/free-programming-books#1768]
Under Objective-C these two links were 404:

- Object-Oriented Programming with Objective-C (PDF)
- Programming With Objective-C

Thanks
GW

**Comment by vhf** [comment]
Thanks!

**Comment by radulemnaru** [comment]
FYI - [English] JavaScript and Node FUNdamentals - Azat Mardanov (Leanpub) states - Book not published
You may not read an unpublished book.

**Comment by switchhax** [comment]
Should  `JavaScript and Node FUNdamentals` be "erased" from the list?

**Comment by KrysD** [comment]
page not found in [LaTeX](https://github.com/vhf/free-programming-books/blob/master/free-programming-books-fr.md#latex) section

> [LaTeX... pour le prof de maths !](http://math.univ-lyon1.fr/irem/IMG/pdf/LatexPourProfMaths.pdf) - Arnaud Gazagnes (PDF)

**Comment by Lond1984** [comment]
[Google's HTML/CSS Style Guide](https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml) is 404. I suggest [Google's GitHub](https://google.github.io/styleguide/htmlcssguide.xml) as a replacement.
