### ISSUE TITLE
Crack down on copyright infringement PDFs

### ISSUE THREAD

**Issue by onebree** [vhf/free-programming-books#1769]
Related to #1683 

I feel we need to crack down on these types of documents, which are mainly PDFs

https://github.com/vhf/free-programming-books/blob/42908b8c92135a765e7bbc9a70979d707f91a8f0/free-programming-books.md#competitive-programming

Copyright included:

> Therefore, no part of this book may be reproduced or transmitted in any form or by any means,
> electronically or mechanically, including photocopying, scanning, uploading to any information
> storage and retrieval system.

**Comment by vhf** [comment]
Definitely. I'm 100% with you. We need to get rid of these. What's the best strategy? 

Checking manually every PDF? Could we somehow split the work?

**Comment by onebree** [comment]
Given that tomorrow (New Year's Day) is a holiday and I am off, I can definitely check some PDFs myself. I think the best thing to do is to add to @borgified's script, checking for `*.pdf`, `dbcontent`, etc. 

Not all PDFs are saved correctly to allow text-searching, so it just _has_ to be done manually.

I do try to help when I see new submissions for the English files, and will take this extra step if it is a PDF.

**Comment by vhf** [comment]
Great, thanks a bunch! I check carefully every new submission but we have a lot of backlog...

**Comment by eshellman** [comment]
The pdf link singled out here is NOT infringing anyone's copyright. It is posted on the author's open website. What the all rights reserved means in this context is you mustn't host the file on another website. You have an implied license to download it and read it, and to link to it, because that's clearly the intent of the rights holder.

You'd be amazed at the number of books advertised as "Open Access" that get scary copyright statements added because no reason. 

I review almost all of the english-language book links that get added here, and, while I'm not a lawyer, I can say that it's a pretty tight ship, no reason for alarm.

**Comment by onebree** [comment]
@eshellman thank you for clarifying that! As you pointed out, they do sound scary, and betterr be safe than sorry!

**Comment by onebree** [comment]
I forgot to post my findings over the weekend! I am no expert in licensing, so the list may include harmless items.

Here they are, English only, before programming languages

- No copyright/license mentioned
  + http://www.jjj.de/fxt/fxtbook.pdf
  + http://igm.univ-mlv.fr/~mac/REC/text-algorithms.pdf
  + http://www.ethoberon.ethz.ch/WirthPubl/CBEAll.pdf
  + http://lampwww.epfl.ch/~schinz/thesis-final-A4.pdf
  + http://www.stack.nl/~marcov/compiler.pdf
  + http://arxiv.org/pdf/1206.1754v2.pdf
  + http://www.csee.umbc.edu/csee/research/cadip/readings/IR.report.120600.book.pdf
  + https://www.ics.uci.edu/~welling/teaching/ICS273Afall11/IntroMLBook.pdf
  + http://home.iitk.ac.in/~arlal/book/nptel/pdf/book_linear.pdf
  + http://www.ii.uib.no/~michal/und/i227/book/book.pdf
  + http://www.math.cornell.edu/~bterrell/dn.pdf
  + http://softwarebyrob.wpengine.netdna-cdn.com/assets/Software_by_Rob%20_How_to_Become_a%20_Programmer_1.0.pdf
  + http://homepages.inf.ed.ac.uk/dts/pm/Papers/nasa-manage.pdf
  + http://www.tac.mta.ca/tac/reprints/articles/22/tr22.pdf
- Simply "copyright"
  + http://algorithmics.lsi.upc.edu/docs/Dasgupta-Papadimitriou-Vazirani.pdf
  + http://www.ethoberon.ethz.ch/WirthPubl/AD.pdf
  + http://www.cs.cmu.edu/~rwh/theses/okasaki.pdf
  + http://www.iro.umontreal.ca/~bengioy/papers/ftml_book.pdf
  + https://www.math.byu.edu/klkuttle/linearalgebra.pdf
  + http://hintjens.wdfiles.com/local--files/main%3Afiles/cc1pe.pdf
  + http://www.di.unipi.it/~ricci/501302.pdf
  + http://artofcommunityonline.org/Art_of_Community_Second_Edition.pdf
  + http://www.st.ewi.tudelft.nl/~arie/phds/Hemel.pdf
  + http://downloads.nakedobjects.net/resources/Pawson%20thesis.pdf
  + http://homepages.inf.ed.ac.uk/dts/pm/Papers/nasa-manage.pdf
  + http://carlos.bueno.org/optimization/mature-optimization.pdf
- Possibly breached copyright
  + http://larc.unt.edu/ian/books/free/lnoa.pdf
  + http://larc.unt.edu/ian/books/free/poa.pdf
  + http://www.comp.nus.edu.sg/~stevenha/myteaching/competitive_programming/cp1.pdf
  + http://wps.aw.com/wps/media/objects/5771/5909832/PDF/Luger_0136070477_1.pdf
  + http://alex.smola.org/drafts/thebook.pdf
  + http://ai.stanford.edu/~nilsson/QAI/qai.pdf
  + http://spivey.oriel.ox.ac.uk/~mike/zrm/zrm.pdf
  + http://www.nobius.org/~dbg/practical-file-system-design.pdf
  + http://www.dreamsongs.com/Files/PatternsOfSoftware.pdf
- Replacements
  + `http://www1.maths.leeds.ac.uk/~charles/statlog/whole.pdf` > `http://www1.maths.leeds.ac.uk/~charles/statlog/`
  + `http://tutorial.math.lamar.edu/pdf/DE/DE_Complete.pdf` > `http://tutorial.math.lamar.edu/Classes/DE/DE.aspx`
  + Maybe removed for a reason?
    * `http://static.fsf.org/nosvn/faif-2.0.pdf` > `https://web.archive.org/web/20151122031019/http://static.fsf.org/nosvn/faif-2.0.pdf`
    * `https://www.sics.se/~joe/thesis/armstrong_thesis_2003.pdf` > `https://web.archive.org/web/20150706063330/https://www.sics.se/~joe/thesis/armstrong_thesis_2003.pdf`
- Unfinished/drafted works
  + http://ciml.info/dl/v0_9/ciml-v0_9-all.pdf
  + http://www.cse.buffalo.edu/~rapaport/Papers/phics.pdf
  + http://www.cs.cmu.edu/~rwh/plbook/book.pdf

**Comment by vhf** [comment]
Many thanks! It will take me quite some time to handle all of these.

I took a random link from "possibly" : `http://www.nobius.org/~dbg/practical-file-system-design.pdf` and it took some digging to find this : "it's now out of print, if you click on the second link you can download a copy" on the book's author webpage... Checking all these will be a long process I guess. :)

**Comment by onebree** [comment]
Yep, this will definitely take a while. What are your thoughts on documents that just sy "Copyright" or &copy; ? I did not do a text search for any terms -- just checked the first few and last few pages.

**Comment by eshellman** [comment]
I'll look through these (slowly) but just looking at the urls...
anything from arxiv.org is cool.
I've previously verified the Open license for the fsf book- "Free as in Freedom".

**Comment by onebree** [comment]
@eshellman I will cross-out the ones you mentioned are good when I have the chance. :-)

**Comment by borgified** [comment]
I keep trying to find an automated solution, this is what I found after a
bit of searching. It's not the complete answer I don't think it'll straight
up tell us if a book is free or not but I think it is a start.

https://openlibrary.org/developers/api

**Comment by eshellman** [comment]
http://www.dreamsongs.com/Files/PatternsOfSoftware.pdf is CC BY-NC-SA per the author's website.

**Comment by eshellman** [comment]
http://spivey.oriel.ox.ac.uk/~mike/zrm/zrm.pdf Copyright © J. M. Spivey, 1988, 1992, 2001.

http://spivey.oriel.ox.ac.uk/~mike/zrm/
The Z Reference Manual has now been allowed to go out of print by the publisher, Prentice Hall, but they have kindly returned the copyright to me, so I can make the full text available here.

**Comment by onebree** [comment]
That's interesting, you have the copyright now? What will it be, CC?

**Comment by eshellman** [comment]
http://ai.stanford.edu/~nilsson/QAI/qai.pdf
from http://ai.stanford.edu/~nilsson/ (author's webpage)
"A free online web version of this book is available at: http://ai.stanford.edu/~nilsson/QAI/qai.pdf. Its pagination is different than that of the print version, but the web version has the advantage that its web links are clickable."

**Comment by eshellman** [comment]
http://larc.unt.edu/ian/books/free/lnoa.pdf
http://larc.unt.edu/ian/books/free/poa.pdf
These are hosted on author's website: http://larc.unt.edu/ian/books/
The license agreement in the files says
"If you wish to provide access to this work in either print or electronic form, you may do so by providing a link to, and/or listing the URL for the online version of this license agreement: http://hercule.csci.unt.edu/ian/books/free/license.html . You may not link to the PDF file."

Of course, the specified url does not exist, but the license can be found at https://larc.unt.edu/ian/books/free/license.html

This sort of license can't be enforced - if so, Google would be infringing. However, for the purposes of FPB, I suggest the url be changed to the (corrected) license url, perhaps with a note to use the drop down menu. Meanwhile, I will reach out to the author and the library at his university, suggesting that other strategies may be more effective.

**Comment by onebree** [comment]
@eshellman some questions

1. What link should we then submit for the `zrm` files?
2. What about the LNOA/POA books?

**Comment by eshellman** [comment]
@onebree for zrm the link we have is fine. (the quote is from the author)
Will submit a PR to change LNO/POA links.

**Comment by vhf** [comment]
`* [Free as in Freedom](https://archive.org/details/faif-2.0) (PDF)` I suggest we keep this one.

@onebree I took the liberty to edit your awesome list to cross a few items!

**Comment by eshellman** [comment]
I think it would be useful to have the urls to check in a PR so that we can comment on them line by line.

**Comment by onebree** [comment]
@eshellman what do you mean by that? In new PRs, or a PR in respect to this post?

**Comment by vhf** [comment]
Good idea @eshellman.
@onebree A PR removing all these links such that we can comment directly on the commit whenever we find a link we should keep.

I'll do this PR as soon as I get home.

**Comment by eshellman** [comment]
or, easier, a PR (which never needs to be accepted) with a file check_copyright containing the urls to check

**Comment by vhf** [comment]
Good idea, even better. Let's talk over there. #1799

**Comment by vhf** [comment]
If anyone speaks a foreign language and wants to check a file for copyright infringement, please do!

**Comment by switchhax** [comment]
Side note: In some file C, C Sharp and C++ are in the wrong "order"; travis won´t like it

**Comment by eshellman** [comment]
I think we're clean. Thanks everyone. File a new issue id there are new concerns.
