### ISSUE TITLE
Add Advent of Code to problem sets doc

### ISSUE THREAD

**Issue by onebree** [vhf/free-programming-books#1773]
http://adventofcode.com/

I would do this myself, but I am unsure which section it would go under.

While it was initially competitive, the public leader board is finished. I think "problem sets" is the better choice, especially since the challenges operate similarly to Project Euler.

What do others think?

**Comment by vhf** [comment]
Problem sets would be a good fit IMO. :+1:

**Comment by onebree** [comment]
@vhf Okay, I will add AOC to the list this weekend. (I'll be home, so I'm more likely to follow through this time :-) )
