### ISSUE TITLE
LISP and Common Lisp

### ISSUE THREAD

**Issue by jay4** [vhf/free-programming-books#1774]
I noticed that books about Common Lisp and also books like SICP are both under the LISP category.

CL and Scheme are two very different languages. Scheme has its own category. Why not Common Lisp? Otherwise, my suggestion would be to rename the LISP category "Common Lisp" and add SICP to the Scheme category.

Awaiting your response. 
Jay

**Comment by vhf** [comment]
Great idea, please do!

**Comment by jay4** [comment]
Cool. When I have time I'll be sure to submit a PR :octocat:

**Comment by jay4** [comment]
I opened up a PR so I guess I can close this issue.
