### ISSUE TITLE
Links direct to 404 pages in Android Section

### ISSUE THREAD

**Issue by hkasera** [vhf/free-programming-books#1797]
In the `free-courses-en.md` in the [`android section`](https://github.com/vhf/free-programming-books/blob/master/free-courses-en.md#android), I noticed that except for the 5th topic i.e *Programming Mobile Services for Android Handheld Systems: Communication* , all the other links take you to 404 pages. This needs to be fixed. 

Also I would like to add few links of my own. Is this a welcome contribution right now?

**Comment by onebree** [comment]
- `https://www.coursera.org/course/androidpart1apps101`
  + https://www.coursera.org/course/androidapps101/
- Coursera mobile cloud computing
  + `https://www.coursera.org/course/mobilecloudprogram`
    * https://www.coursera.org/specializations/mobile-cloud-computing
    * "Mobile Cloud Computing Specialization from Vanderbilt University"
    * The first seven parts are free, while the 8th requires payment (capstone)
  + `https://www.coursera.org/course/android`
    * See above, not yet available on Coursera
  + `https://www.coursera.org/course/androidpart2`
    * See above, not yet available on Coursera
  + `https://www.coursera.org/course/posaconcurrency`
    * https://www.coursera.org/learn/posaconcurrency
  + `https://www.coursera.org/course/posacommunication`
    * https://www.coursera.org/course/posacommunication
    * May eventually move to `coursera.org/learn`
  + https://www.coursera.org/learn/posacontent
  + https://www.coursera.org/learn/mobilecloudprogram
- `https://www.udacity.com/courses#!/android#!/android`
  + https://www.udacity.com/courses/android
  + List of all Android-tagged courses
  + Android nano-degree: https://www.udacity.com/course/android-developer-nanodegree--nd801

**Comment by hkasera** [comment]
Hey @onebree,

All the links are fixed in the section except for the first one. It still shows (https://www.coursera.org/course/androidpart1apps101) instead of (https://www.coursera.org/course/androidapps101/)

Thanks,
Harshita

**Comment by onebree** [comment]
@hkasera I didn't submit a pull request for the change... I only made the list above to help reduce the work for someone else :-)

**Comment by vhf** [comment]
Someone else will take care of it shortly, thanks! ;)

**Comment by hkasera** [comment]
If it is alright, I would like to submit a PR for it.

**Comment by vhf** [comment]
Please do :)
