### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by ajcox** [vhf/free-programming-books#1802]
None of these links are currently working.

Building and Testing with Gradle
Cadmus: A Primer in Java
J Reference Card
Learn Lisp The Hard Way
Learning Go
Object-Oriented Programming with Objective-C
PC-BSD® Users Handbook
Prolog Experiments in Discrete Mathematics, Logic, and Computability
Prolog Tutorial
Theory of Computation

**Comment by onebree** [comment]
@ajcox Can you please add the hyperlinks to your comment above? While they may be dead, it will be easier to search for archives or reposts of.

**Comment by ajcox** [comment]
Sure!

- Building and Testing with Gradle 
 - <https://gradle.org/servicesregistered-access?content=books%2Fbuilding-and-testing%2F>

- Cadmus: A Primer in Java 
 - <http://java.divshot.io/>

- J Reference Card 
 - <http://www.jsoftware.com/jwiki/HenryRich?action=AttachFile&do=view&target=J602_RefCard_color_letter_current.pdf>

- Learn Lisp The Hard Way 
 - <http://learnlispthehardway.org/book/>

- Learning Go 
 - <https://archive.miek.nl/projects/learninggo/index.html>

- Object-Oriented Programming with Objective-C 
 - <https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/OOP_ObjC/OOP_ObjC.pdf>

- PC-BSD® Users Handbook 
 - <http://wiki.pcbsd.org/index.php/PC-BSD%C2%AE_Users_Handbook>

- Prolog Experiments in Discrete Mathematics, Logic, and Computability  - <http://web.cecs.pdx.edu/~jhein/books/PrologLabBook09.pdf>

- Prolog Tutorial 
 - <http://www.cpp.edu/~jrfisher/www/prolog_tutorial/contents.html>

- Theory of Computation 
 - <http://www.cse.iitd.ernet.in/~ssen/csl705/admin705.html>

**Comment by nickbarry** [comment]
The Express book also isn't available at the listed link:
Express.js Guide - Azat Mardanov (Leanpub)
https://leanpub.com/express/read

Hilariously, I see that the book is for sale on Amazon for an affordable $8,734.76:
![image](https://cloud.githubusercontent.com/assets/8515899/12875360/4b03cf80-cd9d-11e5-95f0-7bd3e6c43359.png)

**Comment by johnaoss** [comment]
[An Introduction to the Theory of Computation](http://web.cse.ohio-state.edu/~gurari/theory-bk/theory-bk.html) 404's and so does [Theory of Computation - Sandeep Sen, IIT Delhi](http://www.cse.iitd.ernet.in/~ssen/csl705/admin705.html).

**Comment by borgified** [comment]
thanks for helping clean up bad urls. you can go one small step further and create a pull request with the fixes. more details here:
https://github.com/vhf/free-programming-books/wiki/Other-ways-to-help-(broken-url-cleanup)

**Comment by ollyfg** [comment]
[Learn Lisp The Hard Way]( http://learnlispthehardway.org/book/)
Seems to be back!

**Comment by logicmoo** [comment]
Please keep old and dead links someplace (not just in GIT history) Perhaps
another page?   Since sometimes they do come back.. (Or at least remain
available on wayback machine archive.org)   We will never know they have
returned if the links are gone

**Comment by vhf** [comment]
Sure, don't worry. If a link is down but stays readable through archive.org
I'll always vote for replacing it with this alternative! :)

**Comment by jarrydfillmore** [comment]
Great job!
