### ISSUE TITLE
These are not free

### ISSUE THREAD

**Issue by flik** [vhf/free-programming-books#1860]
When I try to enrol into python https://www.coursera.org/learn/python. They were showing fee.

**Comment by tusharsappal** [comment]
@flik , so there are couple of courses on coursera that are paid , majority of them are free .

We need to check the course contents around this , as this course may be a part of specialization and the overall specialization may be a paid course .

If finally it is a paid one (so it is not free)  , we need to pull back this pull request .  :)

**Comment by vhf** [comment]
I just tried the above link, there's a free option so I'm keeping this link.

![screen shot 2016-03-09 at 11 17 32](https://cloud.githubusercontent.com/assets/2022803/13632153/9587591a-e5e8-11e5-8f65-3319d523be3a.png)
