### ISSUE TITLE
Some free database books from database experts

### ISSUE THREAD

**Issue by asd-and-Rizzo** [vhf/free-programming-books#1882]
Here are these http://www.thethirdmanifesto.com.

**Comment by asd-and-Rizzo** [comment]
Documents and Books
FREE PDF DOWNLOADS

In 2014 Date and Darwen decided to make two of their books freely available in PDF form.  In both cases the text has been slightly revised since publication in book form.  The revisions in question have already been placed at this web site in REFERENCE MATERIAL.  Please note, however, that the definitive version of The Third Manifesto supersedes those to be found in these books; the revisions in the free PDF downloads do not reflect changes to the Manifesto that were made after their original publication.  Thus is history preserved (we hope).

Database Explorations by C.J. Date and Hugh Darwen

Databases, Types, and The Relational Model: The Third Manifesto by C.J. Date and Hugh Darwen

Also free is this one, from O'Reilly:
What is Database Design, Anyway? a free Ebook by C.J. Date (2015).

**Comment by asd-and-Rizzo** [comment]
Or my god! Free books from DB experts rejected! Are you against typed sql?

**Comment by vhf** [comment]
Please open a PR.
