### ISSUE TITLE
Grouping multiple versions of a same file under a common folder

### ISSUE THREAD

**Issue by hkasera** [vhf/free-programming-books#1918]
Hello, 
This repository is a great collection of resources. I have one suggestion as a user to this repository. Currently, the repository has all the files in the root directory. Can we classify the type of files under one folder and organize it? 

For example, we can create a folder, say **free-programming-books** and inside this will have  all the language specific files. Similarly for the **free podcasts screencasts**, **free programming interactive tutorials** and **free courses**. We could have files like **problem-sets-competitive-programming.md** in the root of the repository itself as they do not have multiple versions.

I would love to send a PR if this is a welcome contribution!

Thanks in advance!
Harshita Kasera

**Comment by borgified** [comment]
im subscribing to this thread cuz if this change does happen, then ill need to make some small tweaks to the url checker script to accomodate

**Comment by vhf** [comment]
Hey, sorry for the late answer. Tons of people across the web have direct links to the current files. Moving them around would break too many things.

**Comment by hkasera** [comment]
@vhf Sure, that makes sense! 👍
