### ISSUE TITLE
Translate books from this repository

### ISSUE THREAD

**Issue by iszwnc** [vhf/free-programming-books#1928]
Hi! I created this repository [daily-reading-challenge](https://github.com/iszwnc/daily-reading-challenge) to challenge myself by contributing more to the community. With that said, I'd like to ask permission to use your huge amount of books for translations and adapting them to other languages.

Some credits would've been properly given to you of course! Each book translated will have a link to the original one inside your repository.

Cheers,
João Paulo.

**Comment by eshellman** [comment]
I can't speak for @vhf , but if you want to work on translations, you need to look at the specific license information for each book. For example, if the book is "Copyright, All rights reserved" or "licensed under CC BY-NC-ND" then, although it may be free to read, you do not have the right to create translations. If the book is "licensed under CC BY-SA" or "licensed under CC BY-NC", for example, then you may create and distribute translations provided you comply with the license terms. Keeping track of licenses has been beyond the scope of free-programming-books (can't do everything!!). You may want to look at Unglue.it. which lists books by license, for example, https://unglue.it/free/all/by-sa/

**Comment by vhf** [comment]
@eshellman explained it: translating a book is only allowed when the license for this book allows redistribution of derivative works and this redistribution also needs to respect the book license terms (usually share-alike when derivative works are allowed).

You also might need to respect the license of this repo, depending on how you use it. :)

**Comment by iszwnc** [comment]
@eshellman Thank you! I'll be searching around and hopefully everything will be okay. I'll read more about licenses and stuff to not mess up with both repositories, especially this one, which is way bigger than mine :sweat_smile:

Plus, I'd like somehow inform you @vhf about the book currently translated, any ideas how? Could this repository stay open for future talks? IDK, just wondering some solution...

**Comment by vhf** [comment]
@iszwnc Sure, we can talk here although at some point I'll close this issue. :)

There's also my email address on my github profile, feel free to reach out to me that way!

**Comment by NamPNQ** [comment]
@iszwnc Cool idea :+1:

**Comment by iszwnc** [comment]
In my opinion the idea was great, but the bureaucracy involving it was too much for me. I decided to close this issue and discontinue the repository.

**Comment by iszwnc** [comment]
I will start translating only documentations through out the web and as mentioned following their **Terms & Conditions**.
