### ISSUE TITLE
Changing one link pointing to a commercial resource

### ISSUE THREAD

**Issue by hariharanv01** [vhf/free-programming-books#1930]
The link for one of the .NET resource is pointing to a commercial product.

Resource:
[Practical Performance Profiling: Improving the efficiency of .NET code](http://www.red-gate.com/products/dotnet-development/ants-performance-profiler/entrypage/practical-performance-profiling)

Change the link to "http://www.red-gate.com/products/dotnet-development/ants-performance-profiler/#ebook"

**Comment by switchhax** [comment]
Aren´t those links nearly identical?

**Comment by vhf** [comment]
They are. If this book cannot be obtained for free, it should be removed.

**Comment by switchhax** [comment]
I can do that too tomorrow, if it´s not already done
