### ISSUE TITLE
Adding book to Mathematics

### ISSUE THREAD

**Issue by rluzuriaga** [vhf/free-programming-books#1948]
Category Theory For Scientists:

http://ocw.mit.edu/courses/mathematics/18-s996-category-theory-for-scientists-spring-2013/textbook/MIT18_S996S13_textbook.pdf

**Comment by eshellman** [comment]
should link to online version http://category-theory.mitpress.mit.edu/ which is newer.

**Comment by eshellman** [comment]
And, we've made epub of the online version for unglue.it https://unglue.it/work/160275/

**Comment by switchhax** [comment]
Any associated PR? Or is this issue open for work?

**Comment by vhf** [comment]
@switchhax PR welcome!

**Comment by switchhax** [comment]
Good. Doing it tommorow

**Comment by switchhax** [comment]
Could also be closed, i think ;)
