### ISSUE TITLE
Question about free-programming-interactive-tutorials-pt_BR.md

### ISSUE THREAD

**Issue by switchhax** [vhf/free-programming-books#1964]
Is any work going on with this file? Cause it seems "dead" since last year.

**Comment by vhf** [comment]
I'm sure people still find it useful. Feel free to add resources to it, or remove any dead links. :)

**Comment by switchhax** [comment]
It´s nearly empty...

**Comment by vhf** [comment]
Oh, I didn't notice. Thanks, removing it now.
