### ISSUE TITLE
book Rust have a invalid URL

### ISSUE THREAD

**Issue by uncode** [vhf/free-programming-books#1970]
the book name is 《通过例子学习 Rust》

**Comment by uncode** [comment]
please update it

**Comment by vhf** [comment]
Which one is it? In which file?

**Comment by uncode** [comment]
it is in https://github.com/vhf/free-programming-books/blob/master/free-programming-books-zh.md

category name:Rust
book name:《通过例子学习 Rust》
question: url  http://rust.cc/rust-by-example/  is invalid

**Comment by uncode** [comment]
@vhf
