### ISSUE TITLE
Add place for blogs 

### ISSUE THREAD

**Issue by pridemusvaire** [vhf/free-programming-books#1998]
Hi.

Can you add  place where we can add blogs and medium articles.

**Comment by rollingstones** [comment]
@pridemusvaire Or rather just links to good written articles?

**Comment by BrandtSolovij** [comment]
I'm a crusty old dude, so forgive me if i my coming comment seems... antiquated : "a repository labeled 'free-programming-books' I would not expect to find blog posts"

im closer to half a century of existence than epoch - so please accept this merely as a comment for consideration.

**Comment by pridemusvaire** [comment]
Hi.

Cool no problem.

**Comment by switchhax** [comment]
What are medium articles?

**Comment by pridemusvaire** [comment]
Blogs posts written on medium.com

Regards.

Pride Musvaire 🤓




On Tue, Aug 2, 2016 at 6:28 PM +0200, "Ruben" <notifications@github.com> wrote:












What are medium articles?

**Comment by vhf** [comment]
I think it's outside of the scope of this repository. :)
