### ISSUE TITLE
Python Scripting for Computational Science - Not found

### ISSUE THREAD

**Issue by travismchan** [vhf/free-programming-books#2011]
Python Scripting for Computational Science - Hans Petter Langtangen (PDF) has a broken link.

**Comment by eshellman** [comment]
This link, to the author's github page works. http://hplgit.github.io/primer.html/doc/pub/half/book.pdf

However, it's not clear that the author wants this to be free; the book is password protected on his own website.

**Comment by travismchan** [comment]
Hopefully this gets updated soon.

**Comment by vhf** [comment]
Not sure what to do with this, closing for now. When in doubt, I'd prefer not to include a password protected PDF.
