### ISSUE TITLE
Learn C The Hard Way is not free

### ISSUE THREAD

**Issue by sheeit** [vhf/free-programming-books#2053]
This book is listed here, but it's not free. I followed the [link](https://learncodethehardway.org/c/#buy), and I couldn't get the book without buying it.

**Comment by hugoestr** [comment]
It used to be free until two months ago. This is a change.

**Comment by sdillman** [comment]
Confirmed. Attempting to reach several formerly useful links, such as "c.learncodethehardway.org/book/ex7.html", are all redirected to "learncodethehardway.org/c/" where the book is no longer free.

**Comment by dpavlica** [comment]
It is still freely available at: http://web.archive.org/web/20150203094342/http://c.learncodethehardway.org/book
