### ISSUE TITLE
[Doubt] I want to add a book

### ISSUE THREAD

**Issue by fredkrudger** [vhf/free-programming-books#2199]
@vhf , I have a book called object oriented programming with php5 from Packt Publishing.

Here is the download link =>
 https://mega.nz/#!AI01DJBZ!SW2WU-0gN-I6Bn3hVsYL7nP-HdGvlm7KNEdn2KV45p8

Can I share it?

**Comment by eshellman** [comment]
free-programming-books includes books that are free because the creators want them to be free. It does not include books that are shared without permission. Hope this helps!

**Comment by fredkrudger** [comment]
Thank you for your answer, I understand! Well when you get free content related to courses or books, I will ask if it is apt to upload it.

Thank you very much
