### ISSUE TITLE
PHP is not in the list 

### ISSUE THREAD

**Issue by sayopaul** [vhf/free-programming-books#2277]
Hello I noticed PHP isn't in the list and i was wondering . Its a pretty popular language

**Comment by Jogai** [comment]
Horses were a pretty popular method of traveling when they started building cars...

**Comment by nask0** [comment]
@sayopaul here are [some horses](https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#php).

**Comment by eshellman** [comment]
@sayopaul what @nask0 means to say is that since PHP is in the free programming books category list, perhaps you count be more specific about what list it's not in, or alternatively, just close the issue.
