### ISSUE TITLE
learn sql the hard way is not free

### ISSUE THREAD

**Issue by Asta1986** [vhf/free-programming-books#2295]
https://github.com/vhf/free-programming-books/blob/master/free-programming-books.md#sql-implementation-agnostic --> https://learncodethehardway.org/sql/
I think only the python version is free.

**Comment by eshellman** [comment]
I agree. I'm sure a PR would be appreciated.

**Comment by RomanADavis** [comment]
Yeah. It used to be. I found it really annoying when he took some of his books offline.

**Comment by GCodeur** [comment]
@vhf : you can close this. :)
