### ISSUE TITLE
Algorithms & Datastructures link not working 

### ISSUE THREAD

**Issue by alrosavellana** [vhf/free-programming-books#2317]
Algorithms & Datastructures link is not working in index

**Comment by TrostAft** [comment]
Seems fine on my end. Looking at the raw md for **free-programming-books.md** the link in the index to algorithms and data structures is as follows:

    * [Algorithms & Datastructures](#algorithms--data-structures)

Which works just fine. Although there is a typo here: "Datastructures" should be "Data Structures".

**Comment by eshellman** [comment]
works for me, too
