### ISSUE TITLE
I have download parts of free-programming-books.md. And I share them with Resilio Sync which is p2p file synchronization tool. 

### ISSUE THREAD

**Issue by sancao2** [vhf/free-programming-books#2354]
I have download parts of free-programming-books.md. And I share them with Resilio Sync which is p2p file synchronization tool. The Read Only key is BLXA6HOCLN2XWZDQ6DILEJYWYNMTNGBKM. Welcome to sync it.
The list updates  [here](http://goodshacker.com/free-programming-books/). 
And when I found the bad link or wrong name or bad position, I have PR it. thx.

**Comment by eshellman** [comment]
Thanks for letting us know.
