### ISSUE TITLE
Uploading System

### ISSUE THREAD

**Issue by MHM5000** [vhf/free-programming-books#555]
Hi...
Should we create a server for books that are free but not on the web and people upload them in different services(like Dropbox or Google Drive)?
I can provide the host (a linode server)...

**Comment by xj9** [comment]
If the book is free (and legally distributable) it could be hosted on Archive.org. You could create a collection for free programming-related ebooks and upload them there. File hosting is free with unlimited storage and bandwidth.

**Comment by onebree** [comment]
@xj9 I agree. I do not like personal hosting sites, as there is no way to immediately prove that the source is free and may be distributed online legally.
